### ISSUE TITLE
Contact inputlar qismi

### ISSUE THREAD

**Issue by mukhammadyn** [faithpacifica/Namanganliklar24#15]
https://i.imgur.com/vMhW5gA.png

inputlarga yozilsa shuncha yozilyabdi. Bu xatoni yozib tasvirlab berishga qiynaldim. Inputlarga uzunroq yozuv yozib ko'rsangiz ko'rinadi o'zingizga

**Comment by faithpacifica** [comment]
textarea qismida uzini default borderi ketmadi

**Comment by faithpacifica** [comment]
,keyin uni placeholderiga yozilgan suz negadir kurinmayapti, sababini tushunmayapman
