### ISSUE TITLE
Css 76 qator

### ISSUE THREAD

**Issue by mukhammadyn** [faithpacifica/Namanganliklar24#7]
https://i.imgur.com/EHOc1wU.png

outline:none; qilinmaydi sababi imkoniyati cheklanganlarga screen rider o'qib bermaydi. Outlineni rangi yoqmayabkan bo'lsa outline colorini transparent qilib qo'ysa bo'ladi.

**Comment by faithpacifica** [comment]
outline:transparent qildim
